import type { ApartmentRecord } from "@/types/apartment";

export const DEMO_MODE = !import.meta.env.VITE_CONVEX_URL;

const IMG = (seed: string, w = 1200, h = 800) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const DEMO_APARTMENTS: ApartmentRecord[] = [
  {
    _id: "demo-1",
    title: "Desert Rose Suite",
    titleAr: "جناح وردة الصحراء",
    description: "Luxury suite overlooking the desert mountains of AlUla.",
    descriptionAr: "جناح فاخر بإطلالة على جبال العلا الصحراوية.",
    price: 650,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    area: 120,
    location: "AlUla Old Town",
    locationAr: "ديرة العلا القديمة",
    images: [IMG("alula-suite-1"), IMG("alula-suite-2"), IMG("alula-suite-3")],
    amenities: ["wifi", "parking", "kitchen", "ac", "mountain_view", "tv"],
    rules: ["No smoking"],
    rulesAr: ["ممنوع التدخين"],
    available: true,
    rating: 4.9,
    reviewCount: 132,
    isVerified: true,
    isFeatured: true,
    badges: ["top_rated", "verified"],
  },
  {
    _id: "demo-2",
    title: "Oasis Garden Studio",
    titleAr: "استوديو واحة الحديقة",
    description: "Cozy studio in the heart of AlUla oasis.",
    descriptionAr: "استوديو مريح في قلب واحة العلا.",
    price: 320,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    area: 55,
    location: "AlUla Oasis",
    locationAr: "واحة العلا",
    images: [IMG("alula-oasis-1"), IMG("alula-oasis-2")],
    amenities: ["wifi", "ac", "kitchen", "garden", "coffee_maker"],
    available: true,
    rating: 4.7,
    reviewCount: 86,
    isVerified: true,
    isFeatured: true,
    badges: ["guest_favorite", "verified"],
  },
  {
    _id: "demo-3",
    title: "Dadan Luxury Villa",
    titleAr: "فيلا دادان الفاخرة",
    description: "Private villa for large families near Dadan.",
    descriptionAr: "فيلا خاصة للعائلات الكبيرة قرب دادان.",
    price: 1450,
    bedrooms: 4,
    bathrooms: 3,
    maxGuests: 8,
    area: 320,
    location: "Dadan",
    locationAr: "دادان",
    images: [IMG("alula-villa-1"), IMG("alula-villa-2"), IMG("alula-villa-3")],
    amenities: ["wifi", "parking", "pool", "kitchen", "ac", "terrace", "bbq", "washer"],
    available: true,
    rating: 4.95,
    reviewCount: 58,
    isVerified: true,
    isFeatured: true,
    badges: ["premium", "verified"],
  },
  {
    _id: "demo-4",
    title: "Elephant Rock View",
    titleAr: "إطلالة صخرة الفيل",
    description: "Apartment with direct view of Elephant Rock.",
    descriptionAr: "شقة بإطلالة مباشرة على صخرة الفيل.",
    price: 780,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 5,
    area: 95,
    location: "Elephant Rock",
    locationAr: "صخرة الفيل",
    images: [IMG("alula-rock-1"), IMG("alula-rock-2")],
    amenities: ["wifi", "ac", "mountain_view", "terrace", "stargazing"],
    available: true,
    rating: 4.85,
    reviewCount: 74,
    isVerified: true,
    isFeatured: false,
    badges: ["verified"],
  },
  {
    _id: "demo-5",
    title: "Hegra Explorer's Lodge",
    titleAr: "نُزل مستكشف الحِجر",
    description: "Close to Hegra archaeological site.",
    descriptionAr: "قريب من موقع الحِجر الأثري.",
    price: 540,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    area: 88,
    location: "Hegra",
    locationAr: "الحِجر",
    images: [IMG("alula-hegra-1"), IMG("alula-hegra-2")],
    amenities: ["wifi", "ac", "parking", "coffee_maker", "majlis"],
    available: true,
    rating: 4.75,
    reviewCount: 49,
    isVerified: true,
    isFeatured: false,
    badges: ["new"],
  },
  {
    _id: "demo-6",
    title: "Heritage Village House",
    titleAr: "بيت القرية التراثية",
    description: "Traditional house with modern comfort.",
    descriptionAr: "بيت تراثي براحة عصرية.",
    price: 420,
    bedrooms: 3,
    bathrooms: 2,
    maxGuests: 6,
    area: 140,
    location: "Heritage Village",
    locationAr: "القرية التراثية",
    images: [IMG("alula-heritage-1"), IMG("alula-heritage-2")],
    amenities: ["wifi", "ac", "kitchen", "majlis", "garden"],
    available: true,
    rating: 4.8,
    reviewCount: 63,
    isVerified: true,
    isFeatured: false,
    badges: ["verified"],
  },
];

export const DEMO_STATS = {
  total: DEMO_APARTMENTS.length,
  avgRating: 4.85,
};
