import { mutation } from "./_generated/server";

export const seed = mutation({
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("apartments").first();
    if (existing) return "Already seeded";

    const apartments = [
      {
        title: "Desert Rose Suite — AlUla Heritage Village",
        titleAr: "ج套房 وردة الصحراء — قرية العلا التراثية",
        description:
          "A stunning 2-bedroom apartment nestled in the heart of AlUla's Heritage Village. Floor-to-ceiling windows frame breathtaking views of the ancient sandstone formations. The interior blends modern comfort with traditional Najdi architectural elements — think hand-carved wooden details, earthy terracotta tones, and soft linen fabrics. The open-plan living area flows onto a private terrace overlooking the Oasis. Includes a fully equipped kitchen with premium appliances, spa-inspired bathrooms with rainfall showers, and high-speed WiFi. Perfect for families exploring Hegra, AlUla Old Town, and Dadan.",
        descriptionAr:
          "شقة مذهلة من غرفتي نوم تقع في قلب قرية العلا التراثية. نوافذ من الأرض إلى السقف تframe مناظر خلابة للتكوينات الحجرية الرملية القديمة.",
        price: 650,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 6,
        area: 110,
        location: "Heritage Village",
        locationAr: "القرية التراثية",
        latitude: 26.6172,
        longitude: 37.9158,
        images: [
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "ac",
          "mountain_view",
          "terrace",
          "washer",
          "tv",
        ],
        rating: 4.9,
        reviewCount: 127,
        isVerified: true,
        isFeatured: true,
        badges: ["top_rated", "verified"],
        rules: ["No smoking", "No pets", "Check-in from 3 PM"],
        rulesAr: ["ممنوع التدخين", "ممنوع الحيوانات الأليفة", "تسجيل الدخول من الساعة 3 عصراً"],
        available: true,
      },
      {
        title: "AlUla Cliffside Retreat — Views of Jabal Ithlib",
        titleAr: "ملاذ شرفات العلا — إطلالة على جبل عِصر",
        description:
          "Perched on the dramatic sandstone cliffs overlooking the ancient Nabataean corridor, this luxurious 3-bedroom retreat offers unparalleled views of Jabal Ithlib. The apartment features a unique cave-inspired design with curved walls, ambient lighting, and natural stone accents. The master suite includes a freestanding copper bathtub positioned to capture sunset views. A state-of-the-art kitchen, expansive living room with projection cinema, and a rooftop stargazing deck complete this extraordinary stay. Minutes from Hegra Archaeological Site and AlUla's world-class dining scene.",
        descriptionAr:
          "تقع على المنحدرات الحجرية الرملية المثيرة المطلة على الممر النبطي القديم، وتوفر هذا الملاذ الفاخر من غرف النوم الثلاثة إطلالة لا مثيل لها على جبل عِصر.",
        price: 1200,
        bedrooms: 3,
        bathrooms: 3,
        maxGuests: 8,
        area: 180,
        location: "Jabal Ithlib",
        locationAr: "جبل عِصر",
        latitude: 26.7833,
        longitude: 37.9667,
        images: [
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "ac",
          "mountain_view",
          "pool",
          "washer",
          "tv",
          "bbq",
          "gym",
        ],
        rating: 4.8,
        reviewCount: 89,
        isVerified: true,
        isFeatured: true,
        badges: ["premium", "verified"],
        rules: [
          "No smoking inside",
          "No parties after 11 PM",
          "Maximum 8 guests",
        ],
        rulesAr: [
          "ممنوع التدخين في الداخل",
          "ممنوع الحفلات بعد الساعة 11 مساءً",
          "الحد الأقصى 8 أشخاص",
        ],
        available: true,
      },
      {
        title: "Oasis Garden Studio — AlUla Old Town",
        titleAr: "ستوديو حديقة الواحة —دينة العلا القديمة",
        description:
          "A charming studio apartment in the heart of AlUla Old Town, steps away from ancient alleyways and traditional souqs. This intimate space is perfect for solo travelers or couples seeking an authentic AlUla experience. The apartment features hand-painted ceramic tiles, a cozy sleeping loft, and a private garden courtyard with date palms and a small fountain. Enjoy complimentary traditional Arabic coffee upon arrival. Walking distance to AlUla Museum, Dadan ruins, and the famous Elephant Rock.",
        descriptionAr:
          "شقة استوديو ساحرة في قلب ديرة العلا القديمة، على بُعد خطوات من الأزقة القديمة والأسواق التقليدية.",
        price: 350,
        bedrooms: 1,
        bathrooms: 1,
        maxGuests: 2,
        area: 45,
        location: "AlUla Old Town",
        locationAr: "ديرة العلا القديمة",
        latitude: 26.6153,
        longitude: 37.9217,
        images: [
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
        ],
        amenities: ["wifi", "kitchen", "ac", "garden", "coffee_maker"],
        rating: 4.7,
        reviewCount: 203,
        isVerified: true,
        isFeatured: true,
        badges: ["top_rated", "guest_favorite"],
        rules: ["No smoking", "Quiet hours after 10 PM"],
        rulesAr: ["ممنوع التدخين", "ساعات الهدوء بعد الساعة 10 مساءً"],
        available: true,
      },
      {
        title: "Dadan Luxury Villa — Private Pool & Garden",
        titleAr: "فيلا دادان الفاخرة — مسبح وحديقة خاصة",
        description:
          "An opulent 4-bedroom villa in the prestigious Dadan district, offering absolute privacy and luxury. The property features a temperature-controlled infinity pool overlooking the ancient Dadanite kingdom ruins, manicured desert gardens with native plants, and a full outdoor entertainment area with BBQ and firepit. Inside, you'll find designer furnishings, a chef's kitchen with dual ovens, a home cinema room, and four en-suite bedrooms each with walk-in closets. Ideal for extended families or groups celebrating special occasions in the extraordinary landscape of AlUla.",
        descriptionAr:
          "فيلا فاخرة من أربع غرف نوم في حي دادان الراقي، توفر الخصوصية المطلقة والرفاهية.",
        price: 2200,
        bedrooms: 4,
        bathrooms: 5,
        maxGuests: 10,
        area: 320,
        location: "Dadan",
        locationAr: "دادان",
        latitude: 26.7700,
        longitude: 37.9500,
        images: [
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "ac",
          "pool",
          "garden",
          "bbq",
          "washer",
          "tv",
          "gym",
          "cinema",
          "firepit",
        ],
        rating: 4.95,
        reviewCount: 56,
        isVerified: true,
        isFeatured: true,
        badges: ["premium", "verified", "top_rated"],
        rules: [
          "No smoking inside",
          "No parties",
          "Pool hours 8 AM - 10 PM",
          "Maximum 10 guests",
        ],
        rulesAr: [
          "ممنوع التدخين في الداخل",
          "ممنوع الحفلات",
          "ساعات المسبح من 8 صباحاً حتى 10 مساءً",
          "الحد الأقصى 10 أشخاص",
        ],
        available: true,
      },
      {
        title: "Elephant Rock View Apartment",
        titleAr: "شقة إطلالة على صخرة الفيل",
        description:
          "Wake up to the iconic Elephant Rock right outside your window. This stylish 2-bedroom apartment combines contemporary desert aesthetics with comfort. The open-concept living space features floor-to-ceiling glass panels, terracotta accent walls, and handwoven Saudi textiles. The modern kitchen includes a breakfast bar and premium cookware. Both bedrooms offer blackout curtains and premium mattresses. The rooftop terrace is the highlight — perfect for watching AlUla's legendary sunsets paint the sky in shades of amber and rose.",
        descriptionAr:
          "استيقظ على صخرة الفيل الأيقونية خارج نافذتك مباشرة. هذه الشقة الأنيقة من غرفتي نوم تجمع بين جماليات الصحراء المعاصرة والراحة.",
        price: 780,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 5,
        area: 95,
        location: "Elephant Rock",
        locationAr: "صخرة الفيل",
        latitude: 26.7100,
        longitude: 37.9300,
        images: [
          "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "ac",
          "mountain_view",
          "terrace",
          "washer",
          "tv",
          "coffee_maker",
        ],
        rating: 4.85,
        reviewCount: 164,
        isVerified: true,
        isFeatured: true,
        badges: ["verified", "guest_favorite"],
        rules: ["No smoking", "No pets", "Check-in from 2 PM"],
        rulesAr: [
          "ممنوع التدخين",
          "ممنوع الحيوانات الأليفة",
          "تسجيل الدخول من الساعة 2 عصراً",
        ],
        available: true,
      },
      {
        title: "Hegra Explorer's Lodge — Near Archaeological Site",
        titleAr: "نزل مستكشف الحِجر — بالقرب من الموقع الأثري",
        description:
          "Designed for the adventurous spirit, this earthy 1-bedroom lodge sits just 10 minutes from the Hegra Archaeological Site (Saudi Arabia's first UNESCO World Heritage Site). The interiors celebrate Nabataean craftsmanship with carved stone walls, copper lanterns, and a collection of local art. The compact but fully functional kitchen is stocked with Arabian spices and local dates. A wraparound terrace with daybed offers panoramic views of the surrounding desert landscape. Includes a curated Hegra exploration guide and complimentary stargazing telescope.",
        descriptionAr:
          "مصمم للروح المغامرة، هذا النزل الترابي من غرفة نوم واحدة يقع على بُعد 10 دقائق فقط من الموقع الأثري للحِجر.",
        price: 520,
        bedrooms: 1,
        bathrooms: 1,
        maxGuests: 3,
        area: 65,
        location: "Hegra",
        locationAr: "الحِجر",
        latitude: 26.7847,
        longitude: 37.9500,
        images: [
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "ac",
          "terrace",
          "coffee_maker",
          "stargazing",
        ],
        rating: 4.75,
        reviewCount: 78,
        isVerified: true,
        isFeatured: false,
        badges: ["verified"],
        rules: ["No smoking", "Respect the heritage site"],
        rulesAr: ["ممنوع التدخين", "احترم الموقع التراثي"],
        available: true,
      },
      {
        title: "Maraya Concert Suite — AlUla Arts District",
        titleAr: "ج套房 ماريا الموسيقي — حي الفنون في العلا",
        description:
          "Located in the vibrant AlUla Arts District near the world-famous Maraya concert hall, this chic 2-bedroom suite is perfect for culture enthusiasts. The apartment features a gallery-inspired design with rotating local artwork, a vinyl record collection, and a dedicated music listening corner with premium speakers. Floor-to-ceiling windows showcase views of the mirror-clad Maraya building reflecting the desert landscape. Enjoy pre-concert dinners in the gourmet kitchen or unwind on the balcony with a glass of Saudi dates syrup cocktail.",
        descriptionAr:
          "تقع في حي العلا لل الفني النابض بالحياة بالقرب من قاعة ماريا الشهيرة عالمياً، هذه الج套房 الأنيقة من غرفتي نوم مثالية لمحبي الثقافة.",
        price: 900,
        bedrooms: 2,
        bathrooms: 2,
        maxGuests: 4,
        area: 88,
        location: "AlUla Arts District",
        locationAr: "حي الفنون",
        latitude: 26.6300,
        longitude: 37.9100,
        images: [
          "https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "ac",
          "terrace",
          "tv",
          "washer",
          "coffee_maker",
        ],
        rating: 4.6,
        reviewCount: 112,
        isVerified: true,
        isFeatured: false,
        badges: ["verified", "new"],
        rules: ["No smoking", "No loud music after midnight"],
        rulesAr: ["ممنوع التدخين", "ممنوع الموسيقى العالية بعد منتصف الليل"],
        available: true,
      },
      {
        title: "AlUla Farmhouse Retreat — Organic Garden Living",
        titleAr: "ملاذ المزرعة في العلا — حياة الحديقة العضوية",
        description:
          "Escape to this charming 3-bedroom farmhouse on the outskirts of AlUla, surrounded by ancient date palm groves and organic gardens. The property retains traditional Hejazi architecture with thick stone walls, wooden lattice windows (mashrabiya), and a central courtyard with a centuries-old tree. Wake up to the sound of birdsong and pick fresh herbs from the garden for breakfast. Features include a traditional outdoor majlis, wood-fired pizza oven, and a dipping pool fed by natural springs. Perfect for families seeking a slower, more authentic AlUla experience.",
        descriptionAr:
          "اهرب إلى هذا المزرعة الساحرة من غرف النوم الثلاثة على مشارف العلا، محاطة بحقول النخيل القديمة والحدائق العضوية.",
        price: 850,
        bedrooms: 3,
        bathrooms: 2,
        maxGuests: 8,
        area: 200,
        location: "AlUla Oasis",
        locationAr: "واحة العلا",
        latitude: 26.6200,
        longitude: 37.9050,
        images: [
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
        ],
        amenities: [
          "wifi",
          "parking",
          "kitchen",
          "garden",
          "pool",
          "bbq",
          "majlis",
          "coffee_maker",
        ],
        rating: 4.88,
        reviewCount: 91,
        isVerified: true,
        isFeatured: false,
        badges: ["verified", "guest_favorite"],
        rules: [
          "No smoking inside",
          "Respect the garden",
          "No pets",
        ],
        rulesAr: [
          "ممنوع التدخين في الداخل",
          "احترم الحديقة",
          "ممنوع الحيوانات الأليفة",
        ],
        available: true,
      },
    ];

    for (const apartment of apartments) {
      await ctx.db.insert("apartments", {
        ...apartment,
        available: true,
      });
    }

    return `Seeded ${apartments.length} apartments`;
  },
});
